version: '3.8'

services:
  timestamp-api-node1:
    build:
      context: ../../
      dockerfile: Problem_Set_1/Task_C/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ID=node-1
      - PORT=5000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  timestamp-api-node2:
    build:
      context: ../../
      dockerfile: Problem_Set_1/Task_C/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - NODE_ID=node-2
      - PORT=5000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Load balancer (optional nginx)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - timestamp-api-node1
      - timestamp-api-node2
    restart: unless-stopped